sudo: required
services:
  - docker

before_install:
  - docker build -t rhpvieira/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rhpvieira/react-test npm test -- --coverage

after_success:
  - docker build -t rhpvieira/multi-client  ./client
  - docker build -t rhpvieira/multi-nginx   ./nginx
  - docker build -t rhpvieira/multi-server  ./server
  - docker build -t rhpvieira/multi-worker  ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rhpvieira/multi-client 
  - docker push rhpvieira/multi-nginx
  - docker push rhpvieira/multi-server
  - docker push rhpvieira/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-228788778548
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY